<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>Contensive.CodeMirrorEditor</RootNamespace>
    <AssemblyName>CodeMirrorEditor</AssemblyName>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Contensive.CPBaseClass" Version="26.7.22.34694" />
    <PackageReference Include="Contensive.DbModels" Version="26.7.22.34694" />
  </ItemGroup>
</Project>
